name: Laundry Tracker

on:
    # Runs every 15 minutes or when manually triggered
    schedule:
        - cron: '*/15 * * * *'
    workflow_dispatch:

jobs:
    run-laundry-tracker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile --production

            - name: Run tracker script
              run: bun run start
              env:
                  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
                  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
                  SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
                  ALLIANCELS_AUTH_TOKEN: ${{ secrets.ALLIANCELS_AUTH_TOKEN }}
                  X_API_KEY: ${{ secrets.X_API_KEY }}
                  ROOM_ID: ${{ secrets.ROOM_ID }}
